import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function seedFingerprintPresets() {
  console.log('🌱 Seeding Fingerprint Presets...')

  const presets = [
    // ==========================================================
    // === WINDOWS 11 PRESETS ===
    // ==========================================================
    {
      name: 'Windows 11 - Chrome 140 - NVIDIA RTX 4080',
      description: 'High-end Windows 11 gaming PC with NVIDIA RTX 4080',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
      platform: 'Win32',
      uaPlatform: 'Windows',
      uaPlatformVersion: '15.0.0',
      uaFullVersion: '140.0.6099.71',
      uaMobile: false,
      browserVersion: 140,
      hardwareConcurrency: 16,
      deviceMemory: 32,
      webglVendor: 'NVIDIA Corporation',
      webglRenderer: 'NVIDIA GeForce RTX 4080/PCIe/SSE2',
      screenWidth: 2560,
      screenHeight: 1440,
      colorDepth: 24,
      pixelRatio: 1.0,
      languages: ['en-US', 'en'],
      timezone: 'America/New_York',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 40.7128,
      geolocationLongitude: -74.0060,
      os: 'Windows',
      osVersion: '11',
      isActive: true,
    },
    {
      name: 'Windows 11 - Chrome 140 - Intel UHD Graphics',
      description: 'Standard Windows 11 laptop with Intel integrated graphics',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
      platform: 'Win32',
      uaPlatform: 'Windows',
      uaPlatformVersion: '15.0.0',
      uaFullVersion: '140.0.6099.71',
      uaMobile: false,
      browserVersion: 140,
      hardwareConcurrency: 8,
      deviceMemory: 16,
      webglVendor: 'Intel Inc.',
      webglRenderer: 'Intel(R) UHD Graphics 630',
      screenWidth: 1920,
      screenHeight: 1080,
      colorDepth: 24,
      pixelRatio: 1.0,
      languages: ['en-US', 'en'],
      timezone: 'America/Los_Angeles',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 34.0522,
      geolocationLongitude: -118.2437,
      os: 'Windows',
      osVersion: '11',
      isActive: true,
    },
    {
      name: 'Windows 11 - Chrome 135 - AMD Radeon RX 6800',
      description: 'Windows 11 desktop with AMD Radeon RX 6800',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
      platform: 'Win32',
      uaPlatform: 'Windows',
      uaPlatformVersion: '15.0.0',
      uaFullVersion: '135.0.6099.71',
      uaMobile: false,
      browserVersion: 135,
      hardwareConcurrency: 12,
      deviceMemory: 32,
      webglVendor: 'ATI Technologies Inc.',
      webglRenderer: 'AMD Radeon RX 6800',
      screenWidth: 1920,
      screenHeight: 1080,
      colorDepth: 24,
      pixelRatio: 1.0,
      languages: ['en-US', 'en'],
      timezone: 'America/Chicago',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 41.8781,
      geolocationLongitude: -87.6298,
      os: 'Windows',
      osVersion: '11',
      isActive: true,
    },
    // ==========================================================
    // === macOS PRESETS ===
    // ==========================================================
    {
      name: 'macOS Sonoma - Chrome 140 - Apple M2',
      description: 'MacBook Pro with Apple M2 chip',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
      platform: 'MacIntel',
      uaPlatform: 'macOS',
      uaPlatformVersion: '14.0.0',
      uaFullVersion: '140.0.6099.71',
      uaMobile: false,
      browserVersion: 140,
      hardwareConcurrency: 10,
      deviceMemory: 16,
      webglVendor: 'Apple Inc.',
      webglRenderer: 'Apple M2',
      screenWidth: 2560,
      screenHeight: 1600,
      colorDepth: 24,
      pixelRatio: 2.0,
      languages: ['en-US', 'en'],
      timezone: 'America/Los_Angeles',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 37.7749,
      geolocationLongitude: -122.4194,
      os: 'macOS',
      osVersion: '14',
      isActive: true,
    },
    {
      name: 'macOS Sonoma - Chrome 140 - Apple M3',
      description: 'MacBook Pro with Apple M3 chip',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
      platform: 'MacIntel',
      uaPlatform: 'macOS',
      uaPlatformVersion: '14.0.0',
      uaFullVersion: '140.0.6099.71',
      uaMobile: false,
      browserVersion: 140,
      hardwareConcurrency: 12,
      deviceMemory: 18,
      webglVendor: 'Apple Inc.',
      webglRenderer: 'Apple M3',
      screenWidth: 3024,
      screenHeight: 1964,
      colorDepth: 24,
      pixelRatio: 2.0,
      languages: ['en-US', 'en'],
      timezone: 'America/New_York',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 40.7128,
      geolocationLongitude: -74.0060,
      os: 'macOS',
      osVersion: '14',
      isActive: true,
    },
    {
      name: 'macOS Ventura - Chrome 135 - Intel Iris',
      description: 'MacBook Air with Intel Iris graphics',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
      platform: 'MacIntel',
      uaPlatform: 'macOS',
      uaPlatformVersion: '13.0.0',
      uaFullVersion: '135.0.6099.71',
      uaMobile: false,
      browserVersion: 135,
      hardwareConcurrency: 8,
      deviceMemory: 8,
      webglVendor: 'Intel Inc.',
      webglRenderer: 'Intel Iris Plus Graphics 640',
      screenWidth: 2560,
      screenHeight: 1600,
      colorDepth: 24,
      pixelRatio: 2.0,
      languages: ['en-US', 'en'],
      timezone: 'Europe/London',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 51.5074,
      geolocationLongitude: -0.1278,
      os: 'macOS',
      osVersion: '13',
      isActive: true,
    },
    // ==========================================================
    // === WINDOWS 10 PRESETS ===
    // ==========================================================
    {
      name: 'Windows 10 - Chrome 140 - NVIDIA GTX 1660',
      description: 'Windows 10 gaming PC with NVIDIA GTX 1660',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
      platform: 'Win32',
      uaPlatform: 'Windows',
      uaPlatformVersion: '10.0.0',
      uaFullVersion: '140.0.6099.71',
      uaMobile: false,
      browserVersion: 140,
      hardwareConcurrency: 6,
      deviceMemory: 16,
      webglVendor: 'NVIDIA Corporation',
      webglRenderer: 'NVIDIA GeForce GTX 1660/PCIe/SSE2',
      screenWidth: 1920,
      screenHeight: 1080,
      colorDepth: 24,
      pixelRatio: 1.0,
      languages: ['en-US', 'en'],
      timezone: 'America/New_York',
      canvasMode: 'noise',
      audioContextMode: 'noise',
      webglMetadataMode: 'mask',
      webrtcMode: 'fake',
      geolocationMode: 'fake',
      geolocationLatitude: 40.7128,
      geolocationLongitude: -74.0060,
      os: 'Windows',
      osVersion: '10',
      isActive: true,
    },
  ]

  for (const preset of presets) {
    try {
      await prisma.fingerprintPreset.upsert({
        where: { name: preset.name },
        update: preset,
        create: preset,
      })
      console.log(`✅ Seeded preset: ${preset.name}`)
    } catch (error) {
      console.error(`❌ Failed to seed preset ${preset.name}:`, error)
    }
  }

  console.log(`✅ Seeded ${presets.length} fingerprint presets`)
}

export default seedFingerprintPresets

